

```java
public class Exception01 {  
    public static void main(String[] args) {  
        int num1 = 10;  
        int num2 = 0;  
  
        try {  
            int res = num1 / num2;  
        } catch (Exception e) {  
            // 输出异常信息  
            System.out.println(e.getMessage());  
        }  
  
        System.out.println("程序继续执行");  
    }  
}
```

输出结果如下：
```TEXT
/ by zero
程序继续执行
```